<?php
/**
* @file
* This module is the "Rock, Paper, Scissors" Game functions.
*/


/**
* Implements hook_help.
*
* Displays help and module information.
*
* @param path
*   Which path of the site we're using to display help
* @param arg
*   Array that holds the current path as returned from arg() function
*/
function ebay_rpsgame_help($path, $arg) {
    switch ($path) {
    case "admin/help#ebay_rpsgame":
      return '<p>'.  t("Handles the Game functionality") .'</p>';
      break;
    }
}


/**
* Implements hook_block_info().
*/
function ebay_rpsgame_block_info() {
    $blocks['ebay_rpsgame'] = array(
      'info' => t('Rock, Paper, Scissors'), //The name that will appear in the block list.
      'cache' => DRUPAL_CACHE_PER_ROLE //Default
    );
    return $blocks;
}



/**
* Implements hook_block_view().
*/
function ebay_rpsgame_block_view($delta = '') {
  switch($delta){
    case 'ebay_rpsgame':
      $block['subject'] = t('Rock, Paper, Scissors');
      if(user_access('access content')){
           //Retrieve and process data here.
           //Pass data through theme function.
	   require_once(dirname(__FILE__)."/"."gameexecutor.php");
	   $game = new EbayRPSGameExecutorClass();
	   if ( $game instanceof EbayRPSGameExecutorClass ) {
            $block['content'] = $game->run();
	   }
      }
   } 
  return $block;
}